[package]
name = "ECL"
version = "0.1.0"
authors = ["Alex"]


[lib]
name = "blockchainlib"
path = "src/lib.rs"

[[bin]]
name = "blockchain"
path = "src/main.rs"

[dependencies]
hex = "0.4.3"
crypto-hash = "0.3.3"

